# Game Dimensions
TITLE = "Battle of the Algorithms I"
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
BOARD_WIDTH = 990
BOARD_HEIGHT = 510
GRID_SIZE = 15

# Player Speed
FPS = 60
PLAYER_SPEED_MS = 25

# Food & Obstacles
NUM_FOOD = 3
NUM_OBSTACLES = 10

# Game Duration
GAME_DURATION = 5 * 60 * 1000
PRE_SUDDEN_DEATH_MESSAGE_DURATION = 10 * 1000

# AI Controller Timeout
CONTROLLER_TIMEOUT_MS = 50
CONTROLLER_TIMEOUT_SECONDS = CONTROLLER_TIMEOUT_MS / 1000.0

# AI Update Interval
AI_UPDATE_INTERVAL_MS = PLAYER_SPEED_MS 

# UI Positioning Constants
TITLE_POS_X = SCREEN_WIDTH / 2 - 165
TITLE_POS_Y = 50
SCOREBAR_POS_X = 350
SCOREBAR_POS_Y = 100
PLAYER1_SCORE_POS_X = 150
PLAYER1_SCORE_POS_Y = 100
PLAYER2_SCORE_POS_X = SCREEN_WIDTH - 270
PLAYER2_SCORE_POS_Y = 100
TIMER_POS_X = 20
TIMER_POS_Y = 20
RESTART_BUTTON_X = SCREEN_WIDTH / 2 - 110 
RESTART_BUTTON_Y = 520 