# Game Dimensions
TITLE = "Battle of the Algorithms I - SnakeAI"
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
BOARD_WIDTH = 990
BOARD_HEIGHT = 510
GRID_SIZE = 15

# Player Speed
FPS = 60
PLAYER_SPEED_MS = 25

# AI Controller Timeout
CONTROLLER_TIMEOUT_MS = 50
CONTROLLER_TIMEOUT_SECONDS = CONTROLLER_TIMEOUT_MS / 1000.0

# AI Update Interval
AI_UPDATE_INTERVAL_MS = PLAYER_SPEED_MS 